#ifndef __MVTXP2ALIGN_H__
#define __MVTXP2ALIGN_H__

#include <fun4all/SubsysReco.h>
#include <phool/PHTimeServer.h>
#include <map>
#include <limits.h>

#include <trackbase/TrkrClusterContainer.h>
#include <trackbase/TrkrDefs.h>

class TrkrHitSetContainer;

class MvtxPrototype2Align : public SubsysReco {

public:

  struct AlignmentPar {
    double dx;
    double dy;
    double dz;
  };


  MvtxPrototype2Align(const std::string &name = "MvtxAlign");
  virtual ~MvtxPrototype2Align() {}

  //! module initialization
  int Init(PHCompositeNode *topNode) {return 0;}

  //! run initialization
  int InitRun(PHCompositeNode *topNode);

  //! event processing
  int process_event(PHCompositeNode *topNode);

  //! end of process
  int End(PHCompositeNode *topNode) {return 0;}

  //! put in misalignment by hand
  void AddAlignmentPar(TrkrDefs::hitsetkey key, double dx, double dy, double dz);

  //! print stored misalignments
  void PrintAlignmentPars(std::ostream &os = std::cout) const;

  //! set the directory for alignment parameter files
  void SetAlignmentParFileDir(const std::string fdir) { fdir_ = fdir; }

  //! set boolean to read from file rather than setting by hand
  void SetAlignmentParFromFile(const bool yn) { apff_ = yn; }

  //! set par file name. same for all runs
  void SetAlignmentParFileName(const char* name) { m_afname = name; }

private:

  // read the alignment parameters from file based on run number
  int ReadAlignmentParFile();

  // node tree storage pointers
  TrkrClusterContainer* clusters_;

  // storage object for misalignments
  std::map<TrkrDefs::hitsetkey, AlignmentPar> alignmap_;

  // directory for alignment parameter files
  std::string fdir_;
  int runnumber_;
  bool apff_; // alignment par from file
  std::string m_afname; // alignment par file name. If null generated by run by run

  PHTimeServer::timer _timer;
};

#endif
